import { useState } from 'react'
import { Activity, Database, Download } from 'lucide-react'
import EnvironmentInspector from './EnvironmentInspector.jsx'
import Inspector from './Inspector.jsx'
import LabPanel from './LabPanel.jsx'
import { splineLength } from '../domain/spline.js'
import { bodyEnergy } from '../physics/metrics.js'
import TelemetryChart from './TelemetryChart.jsx'

const format = (value, digits = 2) => Number.isFinite(value) ? value.toFixed(digits) : '—'

function DynamicsPanel({ body, loadState }) {
  const momentumX = body.mass * body.velocity.x
  const momentumY = body.mass * body.velocity.y
  const momentumMag = Math.hypot(momentumX, momentumY)
  const impulseX = body._initialVelocity ? body.mass * (body.velocity.x - body._initialVelocity.x) : 0
  const impulseY = body._initialVelocity ? body.mass * (body.velocity.y - body._initialVelocity.y) : 0
  const impulseMag = Math.hypot(impulseX, impulseY)
  return <section className="metric-stack dynamics-summary" aria-labelledby="dynamics-title">
    <h3 id="dynamics-title" className="visually-hidden">Dynamics for {body.name}</h3>
    <article className="primary-metric"><small>Net force · {body.name}</small><strong>{format(loadState?.forceMagnitude, 3)} <em>N</em></strong></article>
    <div className="metric-row"><article><small>Impulse J (Δp)</small><strong>{format(impulseMag, 3)} N·s</strong></article><article><small>Momentum p</small><strong>{format(momentumMag, 3)} kg·m/s</strong></article></div>
    <div className="metric-row"><article><small>Net torque</small><strong>{format(loadState?.netTorque, 3)} N·m</strong></article><article><small>Angular acceleration</small><strong>{format(body.angularAcceleration, 3)} rad/s²</strong></article></div>
    <div className="metric-row"><article><small>Inertia</small><strong>{format(body.inertia, 4)} kg·m²</strong></article><article><small>Slip error</small><strong>{format(loadState?.slipError ?? 0, 4)} m/s</strong></article></div>
    {body._trackContact && <div className="metric-row"><article><small>Track coordinate</small><strong>{format(body._trackContact.distance, 3)} m</strong></article><article><small>Curvature radius</small><strong>{body._trackContact.curvature ? format(Math.abs(1 / body._trackContact.curvature), 3) : '—'} m</strong></article></div>}
    <p className="dynamics-equation">J = ∫F dt = Δp = mΔv · ΣF = ma</p>
    <div className="force-table-wrap"><table aria-label={`Force and torque components for ${body.name}`}><thead><tr><th>Load</th><th>|F| (N)</th><th>Fx (N)</th><th>Fy (N)</th><th>τ (N·m)</th></tr></thead><tbody>{(loadState?.components ?? []).map((component) => { const offset = { x: component.point.x - body.position.x, y: component.point.y - body.position.y }; const torque = offset.x * component.force.y - offset.y * component.force.x + (component.couple ?? 0); return <tr key={component.id}><th>{component.kind}</th><td>{format(Math.hypot(component.force.x, component.force.y), 2)}</td><td>{format(component.force.x, 2)}</td><td>{format(component.force.y, 2)}</td><td>{format(torque, 3)}</td></tr> })}</tbody></table></div>
  </section>
}

export default function DataRail({ world, selectedId, selectedBody, selectedEntity, connectorState, loadState, eligibleWheels, connectionPortId, history, recordingStatus, pendingTrial, notebook, onArmTrial, onDiscardTrial, onSaveTrial, onDeleteTrial, onExportNotebookJson, onExportNotebookCsv, onSelectEntity, onUpdateBody, onUpdateTrack, onUpdateConnector, onRouteConnector, onUpdateInstrument, onUpdatePort, onPinToWorld, onConnectPort, onUpdateGravity, onRemoveEntity, onUpdateForce, onRemoveForce, onUpdateConstraint, onRemoveConstraint, onPrepareOrbit, onPlaceAtStart, onExport, running }) {
  const [mode, setMode] = useState('energy')
  const [dynamicsMetric, setDynamicsMetric] = useState('netTorque')
  const [kinematicsMetric, setKinematicsMetric] = useState('position')
  const activeBody = selectedBody ?? world.bodies[0]
  const energy = activeBody ? bodyEnergy(activeBody, world.gravity) : { mechanical: 0, translational: 0, rotational: 0, gravitational: 0, height: 0 }
  const speed = activeBody ? Math.hypot(activeBody.velocity.x, activeBody.velocity.y) : 0
  return <aside className="data-rail" aria-label="World data and selected object">
    <div className="data-rail-title"><div><p className="micro-label">Live laboratory</p><h2>Data</h2></div><span><Activity size={15} />120 Hz</span></div>
    <div className="data-mode-switch" role="tablist" aria-label="Measurement family"><button type="button" role="tab" aria-selected={mode === 'energy'} onClick={() => setMode('energy')}>Energy</button><button type="button" role="tab" aria-selected={mode === 'kinematics'} onClick={() => setMode('kinematics')}>Kinematics</button><button type="button" role="tab" aria-selected={mode === 'dynamics'} onClick={() => setMode('dynamics')}>Dynamics</button><button type="button" role="tab" aria-selected={mode === 'lab'} onClick={() => setMode('lab')}>Lab</button></div>
    {mode === 'lab' ? <LabPanel world={world} selectedId={selectedId} recordingStatus={recordingStatus} pendingTrial={pendingTrial} notebook={notebook} onSelect={onSelectEntity} onUpdate={onUpdateInstrument} onRemove={onRemoveEntity} onArm={onArmTrial} onDiscard={onDiscardTrial} onSave={onSaveTrial} onDeleteTrial={onDeleteTrial} onExportJson={onExportNotebookJson} onExportCsv={onExportNotebookCsv} running={running} /> : mode === 'energy' ? <section className="metric-stack"><article className="primary-metric"><small>Total energy · {activeBody?.name ?? 'System'}</small><strong>{format(energy.mechanical)} <em>J</em></strong><span className={Math.abs(world.energyError.percent) < 0.1 ? 'stable' : ''}>System Δ {format(world.energyError.percent, 3)}%</span></article><div className="metric-row"><article><small>Translational KE</small><strong>{format(energy.translational)} J</strong></article><article><small>Rotational KE</small><strong>{format(energy.rotational)} J</strong></article></div><div className="metric-row"><article><small>Gravitational PE</small><strong>{format(energy.gravitational)} J</strong></article><article><small>Height above datum</small><strong>{format(energy.height)} m</strong></article></div><div className="metric-row"><article><small>System total</small><strong>{format(world.metrics.total)} J</strong></article><article><small>Time</small><strong>{format(world.time, 3)} s</strong></article></div><p className="dynamics-equation">ME = ½mv² + ½Iω² + mgh</p></section> : mode === 'kinematics' ? <section className="metric-stack"><article className="primary-metric"><small>Speed · {activeBody?.name ?? 'System'}</small><strong>{format(speed)} <em>m/s</em></strong></article><div className="metric-row"><article><small>Position x</small><strong>{format(activeBody?.position?.x)} m</strong></article><article><small>Position y</small><strong>{format(activeBody?.position?.y)} m</strong></article></div><div className="metric-row"><article><small>Velocity x</small><strong>{format(activeBody?.velocity?.x)} m/s</strong></article><article><small>Velocity y</small><strong>{format(activeBody?.velocity?.y)} m/s</strong></article></div><div className="metric-row"><article><small>Acceleration x</small><strong>{format(activeBody?.acceleration?.x)} m/s²</strong></article><article><small>Acceleration y</small><strong>{format(activeBody?.acceleration?.y)} m/s²</strong></article></div><div className="metric-row"><article><small>Angle</small><strong>{format(activeBody?.angle)} rad</strong></article><article><small>Angular velocity</small><strong>{format(activeBody?.angularVelocity)} rad/s</strong></article></div></section> : <DynamicsPanel body={activeBody} loadState={loadState} />}
    {mode !== 'lab' && activeBody && <section className="data-chart" aria-labelledby="history-chart-title"><div className="rail-section-heading"><span id="history-chart-title">{mode === 'energy' ? `${activeBody.name} energy history` : mode === 'dynamics' ? `${activeBody.name} dynamics history` : `${activeBody.name} kinematics history`}</span><Database size={15} /></div>{mode === 'kinematics' && <label className="select-field"><span>Quantity</span><select value={kinematicsMetric} onChange={(event) => setKinematicsMetric(event.target.value)}><option value="position">Position (m)</option><option value="velocity">Velocity (m/s)</option><option value="acceleration">Acceleration (m/s²)</option><option value="angularVelocity">Angular velocity (rad/s)</option></select></label>}{mode === 'dynamics' && <label className="select-field"><span>Quantity</span><select value={dynamicsMetric} onChange={(event) => setDynamicsMetric(event.target.value)}><option value="impulse">Impulse J (N·s)</option><option value="linearMomentum">Linear momentum p (kg·m/s)</option><option value="netTorque">Net torque (N·m)</option><option value="netForce">Net force (N)</option><option value="angularAcceleration">Angular acceleration (rad/s²)</option><option value="normalForce">Normal force (N)</option><option value="frictionForce">Friction force (N)</option><option value="slipError">Slip error (m/s)</option><option value="trackCoordinate">Track coordinate (m)</option><option value="tensionA">Tension A (N)</option><option value="tensionB">Tension B (N)</option></select></label>}<TelemetryChart history={history} selectedBodyId={activeBody.id} mode={mode} kinematicsMetric={kinematicsMetric} dynamicsMetric={dynamicsMetric} /><button className="data-export" type="button" onClick={onExport}><Download size={15} />Export CSV</button></section>}
    <Inspector entity={selectedEntity} ownerName={selectedEntity?.ownerId ? [...world.bodies, ...world.tracks].find((candidate) => candidate.id === selectedEntity.ownerId)?.name : ''} onSelectOwner={() => selectedEntity?.ownerId && onSelectEntity(selectedEntity.ownerId)} connectorState={connectorState} loadState={loadState} eligibleWheels={eligibleWheels} onRouteConnector={onRouteConnector} onUpdate={(changes) => !selectedEntity ? null : selectedEntity.ownerId ? onUpdatePort(selectedEntity.id, changes) : ['segment', 'spline'].includes(selectedEntity.type) ? onUpdateTrack(selectedEntity.id, changes) : ['spring', 'rope'].includes(selectedEntity.type) ? onUpdateConnector(selectedEntity.id, changes) : onUpdateBody(changes)} onRemove={() => selectedEntity && onRemoveEntity(selectedEntity.id)} canRemove={selectedEntity ? (selectedEntity.ownerId ? Boolean(selectedEntity.custom) : ['segment', 'spline'].includes(selectedEntity.type) || ['spring', 'rope'].includes(selectedEntity.type) || world.bodies.length > 1) : false} running={running} onPlaceAtStart={() => selectedEntity && onPlaceAtStart(selectedEntity.id)} onPinToWorld={() => selectedEntity && onPinToWorld(selectedEntity.id)} connectionPortId={connectionPortId} onConnectPort={(type) => selectedEntity && onConnectPort(selectedEntity.id, type)} />
    <EnvironmentInspector world={world} running={running} onUpdateGravity={onUpdateGravity} onUpdateForce={onUpdateForce} onRemoveForce={onRemoveForce} onUpdateConstraint={onUpdateConstraint} onRemoveConstraint={onRemoveConstraint} onPrepareOrbit={onPrepareOrbit} />
    <section className="assembly-diagnostics" aria-labelledby="assembly-diagnostics-title"><div className="rail-section-heading"><span id="assembly-diagnostics-title">Assembly constraints</span><small>{world.joints.length + world.connectors.length + world.railJoins.length}</small></div>{world.ports.some((port) => port.custom) && <div className="port-shortcuts" aria-label="Custom attachment points">{world.ports.filter((port) => port.custom).map((port) => { const owner = [...world.bodies, ...world.tracks].find((candidate) => candidate.id === port.ownerId); return <button key={port.id} type="button" onClick={() => onSelectEntity(port.id)}>Select {owner?.name ?? port.ownerId} {port.name}</button> })}</div>}{world.diagnostics.length ? <ul className="diagnostic-list">{world.diagnostics.map((message) => <li key={message}>{message}</li>)}</ul> : <p className="environment-help">Topology valid. Run may begin.</p>}{world.joints.map((joint) => <p className="constraint-row" key={joint.id}><strong>{joint.type}</strong><span>{joint.a.portId ?? 'world'} ↔ {joint.b.portId ?? 'world'}</span></p>)}{world.railJoins.map((join) => <p className="constraint-row" key={join.id}><strong>continuous rail</strong><span>{join.a.ownerId}:{join.a.endpoint} ↔ {join.b.ownerId}:{join.b.endpoint}</span></p>)}</section>
    <section className="parallel-data"><div className="rail-section-heading"><span>Objects</span><small>{world.bodies.length}</small></div><table><thead><tr><th>Name</th><th>x</th><th>y</th><th>|v|</th></tr></thead><tbody>{world.bodies.map((body) => <tr key={body.id}><th>{body.name}</th><td>{format(body.position.x, 1)}</td><td>{format(body.position.y, 1)}</td><td>{format(Math.hypot(body.velocity.x, body.velocity.y), 1)}</td></tr>)}</tbody></table></section>
    <section className="parallel-data"><div className="rail-section-heading"><span>Tracks &amp; connectors</span><small>{world.tracks.length + world.connectors.length}</small></div><table><thead><tr><th>Name</th><th>Type</th><th>Length</th></tr></thead><tbody>{world.tracks.map((track) => <tr key={track.id}><th>{track.name}</th><td>{track.type}</td><td>{format(track.type === 'spline' ? splineLength(track) : track.length, 2)}</td></tr>)}{world.connectors.map((connector) => <tr key={connector.id}><th>{connector.name}</th><td>{connector.type}</td><td>{format(connector.type === 'rope' ? connector.length : connector.restLength, 2)}</td></tr>)}</tbody></table></section>
  </aside>
}
