import { useState } from 'react'
import { Activity, Database, Download } from 'lucide-react'
import EnvironmentInspector from './EnvironmentInspector.jsx'
import Inspector from './Inspector.jsx'
import LabPanel from './LabPanel.jsx'
import TelemetryChart from './TelemetryChart.jsx'

const format = (value, digits = 2) => Number.isFinite(value) ? value.toFixed(digits) : '—'

function DynamicsPanel({ body, loadState }) {
  return <section className="metric-stack dynamics-summary" aria-labelledby="dynamics-title">
    <h3 id="dynamics-title" className="visually-hidden">Dynamics for {body.name}</h3>
    <article className="primary-metric"><small>Net torque · {body.name}</small><strong>{format(loadState?.netTorque, 3)} <em>N·m</em></strong></article>
    <div className="metric-row"><article><small>Net force</small><strong>{format(loadState?.forceMagnitude, 3)} N</strong></article><article><small>Angular acceleration</small><strong>{format(body.angularAcceleration, 3)} rad/s²</strong></article></div>
    <div className="metric-row"><article><small>Inertia</small><strong>{format(body.inertia, 4)} kg·m²</strong></article><article><small>Slip error</small><strong>{format(loadState?.slipError ?? 0, 4)} m/s</strong></article></div>
    {body.shape === 'wheel' && <p className="dynamics-equation">Στ = Iα · τrope = (TB − TA)R</p>}
    <div className="force-table-wrap"><table aria-label={`Force and torque components for ${body.name}`}><thead><tr><th>Load</th><th>|F|</th><th>Fx</th><th>Fy</th><th>τ</th></tr></thead><tbody>{(loadState?.components ?? []).map((component) => { const offset = { x: component.point.x - body.position.x, y: component.point.y - body.position.y }; const torque = offset.x * component.force.y - offset.y * component.force.x + (component.couple ?? 0); return <tr key={component.id}><th>{component.kind}</th><td>{format(Math.hypot(component.force.x, component.force.y), 2)}</td><td>{format(component.force.x, 2)}</td><td>{format(component.force.y, 2)}</td><td>{format(torque, 3)}</td></tr> })}</tbody></table></div>
  </section>
}

export default function DataRail({ world, selectedId, selectedBody, selectedEntity, connectorState, loadState, eligibleWheels, connectionPortId, history, recordingStatus, pendingTrial, notebook, onArmTrial, onDiscardTrial, onSaveTrial, onDeleteTrial, onExportNotebookJson, onExportNotebookCsv, onSelectEntity, onUpdateBody, onUpdateTrack, onUpdateConnector, onRouteConnector, onUpdateInstrument, onUpdatePort, onPinToWorld, onConnectPort, onUpdateGravity, onRemoveEntity, onUpdateForce, onRemoveForce, onUpdateConstraint, onRemoveConstraint, onPrepareOrbit, onPlaceAtStart, onExport, running }) {
  const [mode, setMode] = useState('energy')
  const [dynamicsMetric, setDynamicsMetric] = useState('netTorque')
  const kinetic = world.metrics.translationalKinetic + world.metrics.rotationalKinetic
  const momentum = Math.hypot(world.metrics.linearMomentum.x, world.metrics.linearMomentum.y)
  const speed = Math.hypot(selectedBody.velocity.x, selectedBody.velocity.y)
  return <aside className="data-rail" aria-label="World data and selected object">
    <div className="data-rail-title"><div><p className="micro-label">Live laboratory</p><h2>Data</h2></div><span><Activity size={15} />120 Hz</span></div>
    <div className="data-mode-switch" role="tablist" aria-label="Measurement family"><button type="button" role="tab" aria-selected={mode === 'energy'} onClick={() => setMode('energy')}>Energy</button><button type="button" role="tab" aria-selected={mode === 'kinematics'} onClick={() => setMode('kinematics')}>Kinematics</button><button type="button" role="tab" aria-selected={mode === 'dynamics'} onClick={() => setMode('dynamics')}>Dynamics</button><button type="button" role="tab" aria-selected={mode === 'lab'} onClick={() => setMode('lab')}>Lab</button></div>
    {mode === 'lab' ? <LabPanel world={world} selectedId={selectedId} recordingStatus={recordingStatus} pendingTrial={pendingTrial} notebook={notebook} onSelect={onSelectEntity} onUpdate={onUpdateInstrument} onRemove={onRemoveEntity} onArm={onArmTrial} onDiscard={onDiscardTrial} onSave={onSaveTrial} onDeleteTrial={onDeleteTrial} onExportJson={onExportNotebookJson} onExportCsv={onExportNotebookCsv} running={running} /> : mode === 'energy' ? <section className="metric-stack"><article className="primary-metric"><small>Total energy</small><strong>{format(world.metrics.total)} <em>J</em></strong><span className={Math.abs(world.energyError.percent) < 0.1 ? 'stable' : ''}>Δ {format(world.energyError.percent, 3)}%</span></article><div className="metric-row"><article><small>Kinetic</small><strong>{format(kinetic)} J</strong></article><article><small>Potential</small><strong>{format(world.metrics.potential)} J</strong></article></div><div className="metric-row"><article><small>Momentum</small><strong>{format(momentum)} kg·m/s</strong></article><article><small>Time</small><strong>{format(world.time, 3)} s</strong></article></div></section> : mode === 'kinematics' ? <section className="metric-stack"><article className="primary-metric"><small>Speed · {selectedBody.name}</small><strong>{format(speed)} <em>m/s</em></strong></article><div className="metric-row"><article><small>Position x</small><strong>{format(selectedBody.position.x)} m</strong></article><article><small>Position y</small><strong>{format(selectedBody.position.y)} m</strong></article></div><div className="metric-row"><article><small>Velocity x</small><strong>{format(selectedBody.velocity.x)} m/s</strong></article><article><small>Velocity y</small><strong>{format(selectedBody.velocity.y)} m/s</strong></article></div><div className="metric-row"><article><small>Acceleration x</small><strong>{format(selectedBody.acceleration.x)} m/s²</strong></article><article><small>Acceleration y</small><strong>{format(selectedBody.acceleration.y)} m/s²</strong></article></div></section> : <DynamicsPanel body={selectedBody} loadState={loadState} />}
    {mode !== 'lab' && <section className="data-chart" aria-labelledby="history-chart-title"><div className="rail-section-heading"><span id="history-chart-title">{mode === 'energy' ? 'Energy history' : mode === 'dynamics' ? 'Dynamics history' : 'Kinematics history'}</span><Database size={15} /></div>{mode === 'dynamics' && <label className="select-field"><span>Quantity</span><select value={dynamicsMetric} onChange={(event) => setDynamicsMetric(event.target.value)}><option value="netTorque">Net torque</option><option value="netForce">Net force</option><option value="angularAcceleration">Angular acceleration</option><option value="tensionA">Tension A</option><option value="tensionB">Tension B</option></select></label>}<TelemetryChart history={history} mode={mode} dynamicsMetric={dynamicsMetric} /><button className="data-export" type="button" onClick={onExport}><Download size={15} />Export CSV</button></section>}
    <Inspector entity={selectedEntity} ownerName={selectedEntity.ownerId ? [...world.bodies, ...world.tracks].find((candidate) => candidate.id === selectedEntity.ownerId)?.name : ''} onSelectOwner={() => onSelectEntity(selectedEntity.ownerId)} connectorState={connectorState} loadState={loadState} eligibleWheels={eligibleWheels} onRouteConnector={onRouteConnector} onUpdate={(changes) => selectedEntity.ownerId ? onUpdatePort(selectedEntity.id, changes) : selectedEntity.type === 'segment' ? onUpdateTrack(selectedEntity.id, changes) : ['spring', 'rope'].includes(selectedEntity.type) ? onUpdateConnector(selectedEntity.id, changes) : onUpdateBody(changes)} onRemove={() => onRemoveEntity(selectedEntity.id)} canRemove={selectedEntity.ownerId ? Boolean(selectedEntity.custom) : selectedEntity.type === 'segment' || ['spring', 'rope'].includes(selectedEntity.type) || world.bodies.length > 1} running={running} onPlaceAtStart={() => onPlaceAtStart(selectedEntity.id)} onPinToWorld={() => onPinToWorld(selectedEntity.id)} connectionPortId={connectionPortId} onConnectPort={(type) => onConnectPort(selectedEntity.id, type)} />
    <EnvironmentInspector world={world} running={running} onUpdateGravity={onUpdateGravity} onUpdateForce={onUpdateForce} onRemoveForce={onRemoveForce} onUpdateConstraint={onUpdateConstraint} onRemoveConstraint={onRemoveConstraint} onPrepareOrbit={onPrepareOrbit} />
    <section className="assembly-diagnostics" aria-labelledby="assembly-diagnostics-title"><div className="rail-section-heading"><span id="assembly-diagnostics-title">Assembly constraints</span><small>{world.joints.length + world.connectors.length}</small></div>{world.ports.some((port) => port.custom) && <div className="port-shortcuts" aria-label="Custom attachment points">{world.ports.filter((port) => port.custom).map((port) => { const owner = [...world.bodies, ...world.tracks].find((candidate) => candidate.id === port.ownerId); return <button key={port.id} type="button" onClick={() => onSelectEntity(port.id)}>Select {owner?.name ?? port.ownerId} {port.name}</button> })}</div>}{world.diagnostics.length ? <ul className="diagnostic-list">{world.diagnostics.map((message) => <li key={message}>{message}</li>)}</ul> : <p className="environment-help">Topology valid. Run may begin.</p>}{world.joints.map((joint) => <p className="constraint-row" key={joint.id}><strong>{joint.type}</strong><span>{joint.a.portId ?? 'world'} ↔ {joint.b.portId ?? 'world'}</span></p>)}</section>
    <section className="parallel-data"><div className="rail-section-heading"><span>Objects</span><small>{world.bodies.length}</small></div><table><thead><tr><th>Name</th><th>x</th><th>y</th><th>|v|</th></tr></thead><tbody>{world.bodies.map((body) => <tr key={body.id}><th>{body.name}</th><td>{format(body.position.x, 1)}</td><td>{format(body.position.y, 1)}</td><td>{format(Math.hypot(body.velocity.x, body.velocity.y), 1)}</td></tr>)}</tbody></table></section>
    <section className="parallel-data"><div className="rail-section-heading"><span>Tracks &amp; connectors</span><small>{world.tracks.length + world.connectors.length}</small></div><table><thead><tr><th>Name</th><th>Type</th><th>Length</th></tr></thead><tbody>{world.tracks.map((track) => <tr key={track.id}><th>{track.name}</th><td>track</td><td>{format(track.length, 2)}</td></tr>)}{world.connectors.map((connector) => <tr key={connector.id}><th>{connector.name}</th><td>{connector.type}</td><td>{format(connector.type === 'rope' ? connector.length : connector.restLength, 2)}</td></tr>)}</tbody></table></section>
  </aside>
}
